apiVersion: v1
kind: Service
metadata:
  name: sign-language-converter-service
  labels:
    app: sign-language-converter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: sign-language-converter

